#!/usr/bin/python
__author__ = 'Lee Cai'

#This little code fraction is for checking whether two words are anagram

string1 = 'mary'
string2 = 'armyt'

def count_letters(string):
	string_set = set(list(string))
	letter_counts = {}	
	for i in string_set:
		letter_counts[i] = string.count(i)
	return (string_set,letter_counts)

#prnt is used for controling output
def check_annagrams(string1, string2, prnt = 1):
	if len(string1) != len(string2):
		if prnt == 1:
			print 'The two strings %s and %s are not annagrams.' %(string1,string2)
		return False
	else:
		string1_tup = count_letters(string1)
		string2_tup = count_letters(string2)
		if string1_tup[0].issubset(string2_tup[0]) and string2_tup[0].issubset(string1_tup[0]):
			for i in string1_tup[0]:
				if string1_tup[1][i] == string2_tup[1][i]:
					continue
				else:
					if prnt == 1:
						print 'hah The two strings %s and %s are not annagrams.' %(string1,string2)
					return False
			if prnt == 1:
				print 'The two strings %s and %s are annagrams.' %(string1,string2)
			return True
		else:
			if prnt == 1:
				print 'The two strings %s and %s are not annagrams.' %(string1,string2)
			return False

print check_annagrams(string1,string2, prnt = 1)



